# Generated by Django 5.2.17 on 2026-09-09 14:41

import re

from django.db import migrations, models

NAME_PATTERN = re.compile(r"^(?P<code>.+?)-(?P<year>\d+)(?P<letter>[A-C])$", re.IGNORECASE)


def split_existing_names(apps, schema_editor):
    """Recover branch/year/section from names already in the database.

    Sections were previously identified only by a composite string such as
    "CSE-3B". Pull the year and letter back out of it so the new structured
    fields agree with the name before the unique constraint lands.
    """
    ClassSection = apps.get_model("academics", "ClassSection")
    for section in ClassSection.objects.all():
        match = NAME_PATTERN.match(section.name or "")
        if not match:
            # Unparseable name: leave the defaults and let the operator fix it
            # rather than silently inventing a year.
            continue
        section.year = int(match.group("year"))
        section.section_letter = match.group("letter").upper()
        section.save(update_fields=["year", "section_letter"])


def restore_names(apps, schema_editor):
    """Reverse step: the name already holds everything, so nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsection',
            options={'ordering': ['department__code', 'year', 'section_letter'], 'verbose_name': 'class section'},
        ),
        migrations.AddField(
            model_name='classsection',
            name='section_letter',
            field=models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='name',
            field=models.CharField(editable=False, help_text='Generated from branch, year and section — e.g. CSE-3B.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')], default=1),
        ),
        migrations.RunPython(split_existing_names, restore_names),
        migrations.AddConstraint(
            model_name='classsection',
            constraint=models.UniqueConstraint(fields=('department', 'year', 'section_letter'), name='uniq_department_year_section'),
        ),
    ]
