# Generated by Django 5.2.17 on 2026-09-09 13:30

import apps.face.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField()),
                ('image', models.ImageField(upload_to=apps.face.storage.enrollment_image_path)),
                ('det_score', models.FloatField()),
                ('quality_score', models.FloatField(help_text='Laplacian variance of the face crop — higher is sharper.')),
                ('brightness', models.FloatField(default=0.0)),
                ('face_width', models.PositiveIntegerField(default=0)),
                ('pose', models.CharField(choices=[('FRONT', 'Looking straight'), ('LEFT', 'Turned slightly left'), ('RIGHT', 'Turned slightly right'), ('UP', 'Tilted up'), ('ALT', 'Straight, different lighting')], default='FRONT', max_length=8)),
                ('step_index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_enrollments', to='students.student')),
            ],
            options={
                'ordering': ['student', 'step_index'],
                'constraints': [models.UniqueConstraint(fields=('student', 'step_index'), name='uniq_student_enrollment_step')],
            },
        ),
    ]
